defaults:
  - _self_
  - experiment: null
  - override hydra/launcher: submitit_slurm
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

data: embed128_flattours
embed128_csv_path: /root/autodl-tmp/mapper/train_embeds128.csv
val_csv_path: /root/autodl-tmp/mapper/test_embed128.csv

earth_datadir: /checkpoint/${oc.env:USER}/data/earth_data
rna_datadir: /checkpoint/${oc.env:USER}/data/rna
top500_datadir: /checkpoint/${oc.env:USER}/data/top500
mesh_datadir: /checkpoint/${oc.env:USER}/data/mesh
data_seed: null
wrapped:
  dim: 5
  n_mixtures: 1
  scale: 0.2
mesh:
  numeigs: 100
  metric: biharmonic
  temp: 0.25
  nsteps: 200
  time_eps: 1e-5
  projx: True
  method: euler
  atol: 1e-5
  rtol: 1e-5

model:
  d_model: 256
  num_layers: 4
  actfn: swish
  fourier: null
  atol: 1e-5
  rtol: 1e-5
  metric_normalize: True

optim:
  num_iterations: 50000
  batch_size: 256
  val_batch_size: 2048
  scheduler: cosine
  grad_clip: 0.0
  lr: 5e-5
  wd: 1e-4
  eps: 1e-8
  ema_decay: 0.999

div_mode: exact
normalize_loglik: False
early_stopping_patience: 1000

use_wandb: False
resume: null
seed: 0

val_every: 2000
ckpt_every: null
visualize: null

eval_projx: True
local_coords: False

hydra:
  job:
    chdir: True
  run:
    dir: ./outputs/runs/${data}/fm/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: ./outputs/multiruns/${data}/fm/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    # max_num_timeout: 100000
    timeout_min: 4319
    cpus_per_task: 10
    gpus_per_node: 1
    nodes: 1
    partition: learnlab
    constraint: volta32gb